### ISSUE TITLE
Define sections for template parsing.

### ISSUE THREAD

**Issue by jsgv** [martini-contrib/render#46]
I am trying to define code blocks that will get injected in the base template if they are defined. I don't want to include all the scripts that are required on one page onto another that doesn't require it.

Basically what im trying to do is something like:

on the layout: `admin.tmpl`:

``` go
<script src="jquery.min.js"></script>
<script src="scripts.min.js"></script>
{{ footer_extra }}
```

and on `new.tmpl`:

``` go
{{define "footer_extra"}}
  <!-- scripts just for this page -->
  <script src="script-1.js"></script>
  <script src="script-2.js"></script>
  <script src="script-3.js"></script>
{{end}}
```

Not sure if this is something i could just achieve with Go, kinda new to the language.
Thanks!

**Comment by jesusjjf** [comment]
Figured it out.

**Comment by jesusjjf** [comment]
I noticedI noticed that I cant define more than one template, which kinda defeats what I'm trying to achieve.

`index.tmpl`
```go
{{define "footer_extra"}}
  <!-- scripts just for this page -->
  <script src="script-1.js"></script>
  <script src="script-2.js"></script>
{{end}}
```

`new.tmpl`
```go
{{define "footer_extra"}}
  <!-- scripts just for this page -->
  <script src="script-3.js"></script>
  <script src="script-4.js"></script>
{{end}}
```

`layout.tmpl`
```go
<script src="main.js"></script>
{{template "footer_extra"}}
```

will throw an `PANIC`
`template: redefinition of template "footer_extra"`

**Comment by dariusc93** [comment]
@jesusjjf Was this ever resolved?
