### ISSUE TITLE
Missing return at end of function

### ISSUE THREAD

**Issue by ghost** [martini-contrib/render#56]
`./main.go:35: missing return at end of function`

```
    m.Get("/test", func (r render.Render) string {
        r.HTML(200, "index", "world")
    })
```

I can't seem to figure out the problem here, any ideas?

**Comment by unknwon** [comment]
You are defining your handler returns a string, but you didn't anything.

**Comment by ghost** [comment]
@Unknwon Yeah, just noticed. Embarrassing, hah.
